### ISSUE TITLE
The time is stripped from the due date

### ISSUE THREAD

**Issue by FeikoJoosten** [myntath/gtasks-ha#10]
I would love to add support for sending a notification on my phone once the specific due date of a task is reached. However, for this I also require the timestamp, but looking at the code the timestamps is being stripped from the due date.

## Version of the custom_component

0.6.1

## Configuration

```yaml

N/A

```

## Describe the bug
The code [here](https://github.com/myntath/gtasks-ha/blob/master/custom_components/gtasks/sensor.py#L91) clearly strips away the timestamp from the due date.

## Debug log

```text

N/A

```

**Comment by myntath** [comment]
I don't believe this can be fixed. See https://developers.google.com/tasks/reference/rest/v1/tasks under 'due'

`Due date of the task (as a RFC 3339 timestamp). Optional. The due date only records date information; the time portion of the timestamp is discarded when setting the due date. It isn't possible to read or write the time that a task is due via the API.`

Until google changes its mind about this we are stuck.

**Comment by FeikoJoosten** [comment]
That's just bonkers. Found a related issue thread it's been like this since at least 2019... 
according to [this comment](https://issuetracker.google.com/issues/128979662#comment85) they use the calendar for storing the time. Maybe there's something there? Otherwise feel free to close this issue as it's clearly out of your hands.

**Comment by myntath** [comment]
Yes unfortunately Google is not up to standard on this one.
