### ISSUE TITLE
Reboot of HA creates an empty new Devices

### ISSUE THREAD

**Issue by Bastian007** [myntath/gtasks-ha#3]
-->

## Version of the custom_component
v0.6.0

## Describe the bug
Per reboot of HA the integration shows another (empty) device
<img width="189" alt="issue_devicecreatiuonatreboot" src="https://user-images.githubusercontent.com/12425311/225653302-251d233d-a782-490b-b22e-ce9edc5231c8.PNG">

**Comment by myntath** [comment]
Confirming I'm getting this behaviour as well.

**Comment by myntath** [comment]
I believe I've fixed this in the latest commit.
