### ISSUE TITLE
Error in googleapi.py???

### ISSUE THREAD

**Issue by stofakiller** [myntath/gtasks-ha#6]
I come to the google page where to give access/accept the integration, but when i press next, it redirect me to localhost, as i can see thats in the file gtasks_api.py in line 43... So i cant get the auth to work in HA... It that just me, or is it a bug?

**Comment by myntath** [comment]
This is currently expected (although not ideal) behaviour. See point  9 in the instructions.

> Authenticate and once you reach a 404 page not found look at the url and copy and paste the code between 'code=' and '&scope='.

**Comment by stofakiller** [comment]
Just saw that but i also triede that before, and get a Unknown error occurred

I'll try to delete it again, reboot and start all over :-) Thanks for your quick reply

**Comment by stofakiller** [comment]
Nope, after i put in my auth return code, i still get an unknown error occurred

**Comment by myntath** [comment]
If you've got the auth code from google then this is likely a different issue now. I would suggest trying to see if there is anything in the home assistant log. 

Issue #2 may also be related and so it may be worth deleting your 'token.pickle' file and setting everything up again.

**Comment by stofakiller** [comment]
Found something in the logs for Gtask, you have to enable the "Google Tasks API", i had only the calendar enabled

json returned "**Tasks API has not been used in project xxxxxxxxxxxx1 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/tasks.googleapis.com/overview?project=xxxxxxxxxxxxxxx then retry**.

**Comment by myntath** [comment]
Great to hear! I'll close this and I will at some point make some detailed instructions of setting up the Google credentials.
