### ISSUE TITLE
Credentials file not found

### ISSUE THREAD

**Issue by dnestico** [myntath/gtasks-ha#8]
## Version of the custom_component

Latest

## Describe the bug
No matter where I put the credentials file the integration can never find it, impossible to install. I have other Google integrations but I made a new Auth Key for this integration, I put in the /www/ folder, can't find it, I put it in its own folder, and it still can't find it. Idk what to do.

<img width="571" alt="Screenshot 2023-08-08 at 4 56 22 PM" src="https://github.com/myntath/gtasks-ha/assets/3034555/1987cd83-a1ba-4586-86a2-c626a60d60ae">

<img width="614" alt="Screenshot 2023-08-08 at 4 53 29 PM" src="https://github.com/myntath/gtasks-ha/assets/3034555/669579fe-c37b-414f-b674-4f7fb585055c">

**Comment by myntath** [comment]
It looks to me like the path is wrong. Does your home assistant run from www? if so then ./credentials/credentials.json would be correct. Perhaps just try using the full path name '/var/www/credentials/credentials.json' or whatever it might be above www.

Also the location of the file must be writable by home assistant.

**Comment by dnestico** [comment]
I tried putting it in the custom_compents HACs folder as the docs say too but it kept giving me permission errors. 



> /www/credentials/credentials.json'
This didn't work, local and www are the same thing btw.

> Also the location of the file must be readable by home assistant, so make sure to check the permissions of that folder hierarchy.
I wonder if this is the issue, I'm running HA on Unraid docker and am able to upload files and edit them just fine but maybe something different here. 

> It looks to me like the path is wrong. Does your home assistant run from www? if so then ./credentials/credentials.json would be correct. Perhaps just try using the full path name '/www/credentials/credentials.json' if that is the full path name.
> 
I don't think so, here's what it looks like....

<img width="1006" alt="Screenshot 2023-08-09 at 12 43 13 AM" src="https://github.com/myntath/gtasks-ha/assets/3034555/446c3896-4763-401f-af58-f2b16dbcfef3">

**Comment by myntath** [comment]
I'm not very familiar with docker unfortunately and I suspect the path names are somewhat different to normal but it should still work I believe.

That folder on the right is usually where I place my credentials.json and for my install the relative path is just './credentials.json' if you haven't tried that yet it might be worth a shot.

You could also try to see if you are getting an error message in your logs. I do in some situations but not always, I think if HA can't read the file I see an error but if it can't read the folder nothing is shown.

**Comment by dnestico** [comment]
Sorry for the trouble.

Moving it outside of any folder and just in the main container folder worked!

<img width="498" alt="Screenshot 2023-08-09 at 2 05 34 AM" src="https://github.com/myntath/gtasks-ha/assets/3034555/10609d49-fac2-4b3d-8b53-356b347f8379">

**Comment by dnestico** [comment]
Apologies for commenting on a closed issue, this will be the last I swear lol.

But is it only possible to just add 1 list right now or can I make it import all of them?

**Comment by myntath** [comment]
You can add more than one. Select the list. Uncheck the 'check to finish setup box'. Click submit. Repeat.

Once setup though you can't later add more lists (future feature). If you want to add more later, delete and then add again.
